# Site settings
title: Jonathan's Blog
SEOTitle: Jonathan's Blog | CoDe1230
header-img: img/oriental-pearl-tower-wallpaper-1.jpg
email: caozengjie@outlook.com
description: "Computational Design | Z5173508"
keyword: "Code, code, 1230, Jonathan, Z5173508, 5173508, z5173508"
url: "https://jonathan1230.top"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/grasscaograss/grasscaograss.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Love Lila!"
sidebar-avatar: https://github.com/grasscaograss/grasscaograss.github.io/blob/master/img/Lila.jpg?raw=true     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     u/5444445211?refer_flag=1001030201_&is_hot=1
github_username:    grasscaograss




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important




# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 5692b05d68511b41f3a3                      #生成的clientID
  clientSecret: fc26a1bbb0dafa736d1c28171cb57cbe637cf681   #生成的clientSecret
  repo:  grasscaograss.github.io   #仓库名称
  owner: grasscaograss    #github用户名
  admin: grasscaograss
  distractionFreeMode: true #是否启用类似FB的阴影遮罩




# Analytics settings


# Google Analytics
ga_track_id: 'UA-123132494-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Group Members
friends: [
    {
        title: "Blair",
        href: "https://blairhuang.github.io/code1230/"
    },{
        title: "Teresa",
        href: "https://z5211269.github.io/CODE1230/"
    },{
        
    }
]
